### PR TITLE
Https support

### PR DESCRIPTION
**Pull request by solocommand**
Adds support and basic documentation for using a self-signed certificate with the `marko-web` package.

image

### CODE REVIEW

**Review by zarathustra323 — COMMENTED** [review]
What was the impetus for adding HTTPS here?

**Comment by solocommand** [comment]
> What was the impetus for adding HTTPS here?

Needed to troubleshoot how some third-party code would work when running in an insecure context (https on the page, loaded via http)

**Comment by solocommand** [comment]
[Update legacy insecure resources to use secure versions (Mixed Content warnings)](https://trello.com/c/UTT8UqTj/1-update-legacy-insecure-resources-to-use-secure-versions-mixed-content-warnings)

**Comment by zarathustra323** [comment]
@solocommand Let's discuss in more detail on a call

**Pull request closed without merging**
