### PR TITLE
Support additional search page translations

### PR DESCRIPTION
**Pull request by Shinsina**
Search-Page-1
Search-2
Search-Lower
Filters-Search

Screenshots from BLP (A site without an i18n function definition):
Screen Shot 2022-11-03 at 9 26 03 AM
Screen Shot 2022-11-03 at 9 26 09 AM
Screen Shot 2022-11-03 at 9 26 34 AM
Screen Shot 2022-11-03 at 9 26 40 AM
Screen Shot 2022-11-03 at 9 26 51 AM
Screen Shot 2022-11-03 at 9 27 17 AM

Screenshots from AW (A site with an i18n function definition but is not translated (remains the same as before)):
Screen Shot 2022-11-03 at 9 30 16 AM
Screen Shot 2022-11-03 at 9 30 20 AM
Screen Shot 2022-11-03 at 9 30 40 AM
Screen Shot 2022-11-03 at 9 30 45 AM
Screen Shot 2022-11-03 at 9 30 54 AM
Screen Shot 2022-11-03 at 9 30 59 AM

### CODE REVIEW

**Comment by Shinsina** [comment]
[Mundo site translations needed](https://trello.com/c/d5s711ly/478-mundo-site-translations-needed)

**Comment by brandonbk** [comment]
@Shinsina - have you spun up this new version against a site other than Mundo? Just want to confirm the English versions of everything remain unaffected.

**Comment by Shinsina** [comment]
> @Shinsina - have you spun up this new version against a site other than Mundo? Just want to confirm the English versions of everything remain unaffected.

@brandonbk I had run this against both PackWorld and Automation World as my English Test sites and everything was unaffected. Under the hood the i18n function on the Marko side just falls back to the value passed into it if no translation and/or translation function are provided.


EDIT: Need to confirm as to what happens if i18n is not defined in the site's start-server, forget there are cases in which base-cms-marko-web-search is used in which an i18n function is not defined, this currently stands to be a backwards breaking change as it requires an i18n function to be defined.

**Comment by Shinsina** [comment]
@brandonbk Have adjusted these changes to no longer require the definition of an i18n function for them to work (see screenshots from BLP above), English sites remain unchanged (as the default i18n function is simply take the value passed in and use that)

**Review by brandonbk — APPROVED** [review]

**Pull request merged**
