### PR TITLE
Add mutation to set event dates

### PR DESCRIPTION
**Pull request by solocommand**
Recreate #123 without mutation handling

image

### CODE REVIEW

**Comment by solocommand** [comment]
[Create GraphQL mutations to allow modification of company and event fields](https://trello.com/c/MNb1mVwT/101-create-graphql-mutations-to-allow-modification-of-company-and-event-fields)

**Comment by zarathustra323** [comment]
@solocommand it looks like the build is failing because travis cannot find the remote branch?

**Review by zarathustra323 — COMMENTED** [review]
@solocommand this looks good except for the conflicts

**Comment by solocommand** [comment]
> @solocommand it looks like the build is failing because travis cannot find the remote branch?

I pushed to p1 org first and deleted the branch, the branch test failed but the PR build was fine

**Review by zarathustra323 — APPROVED** [review]

**Pull request merged**
